<?php
$authViewModel->getForm()->setAttributes ( array (
    'method' 	=> 'post',
    'class' 	=> 'form-horizontal',
    'id'	=> 'loginForm',
) );
$authViewModel->getForm()->prepare ();
?>

<div class="panel panel-default text-center">
    <div class="panel-heading">
      <h3 class="panel-title">Login</h3>
    </div>
    <div class="panel-body">
        <section id="loginFormSection">
            <?= $this->form ()->openTag ( $authViewModel->getForm() );?> 
                <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('Email')->setAttribute("ng-model","Email")); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('Email')); ?> 
                </div>
                <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('Password')); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('Password')); ?> 
                </div>
                <div class="form-group">
                    <input type="button" onclick="(function() { require('./home/home').submitLoginForm('<?= $this->url('home',array('action' => 'login'));?>') })()" value="Login" class="btn btn-primary" />
                    &nbsp;&nbsp;<a onclick="(function(){require('./home/home').registerForm('<?= $this->url('home', array('action'=>'register')); ?>')})()" href="#">Register</a>
                </div>
            <?= $this->form ()->closeTag ();?><!-- form -->
            <?php if (!is_null($authViewModel->getErrorMessage())){
            echo $this->partial("error/_information.phtml", array('message' => $authViewModel->getErrorMessage()));}?>
        </section><!-- content -->
    </div>
</div>
