<?php

$authViewModel->getForm()->setAttributes ( array (
    'method' 	=> 'post',
    'class' 	=> 'form-horizontal',
        'id'		=> 'registerForm'
) );
$authViewModel->getForm()->prepare ();
?>
<div class="panel panel-default text-center">
    <div class="panel-heading">
      <h3 class="panel-title">Register</h3>
    </div>
    <div class="panel-body">
        <section id="registerFormSection">
            <?= $this->form ()->openTag ( $authViewModel->getForm() );?> 
               <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('FirstName')); ?>
                    <?= $this->formElementErrors($authViewModel->getForm()->get('FirstName')); ?> 
                </div>
               <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('LastName')); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('LastName')); ?> 
                </div>
               <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('Email')); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('Email')); ?> 
                </div>
               <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('Password')); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('Password')); ?> 
                </div>
               <div class="form-group">
                    <?= $this->formElement($authViewModel->getForm()->get('repassword')); ?>   
                    <?= $this->formElementErrors($authViewModel->getForm()->get('repassword')); ?> 
                </div>
                <div class="form-group">
                    <input type="button" onclick="(function() { require('./home/home').submitRegisterForm('<?= $this->url('home',array('action' => 'register'));?>') })()" value="Register" class="btn btn-primary" />
                    <a href="<?= $this->url('root', array('action' => 'index')); ?>">Log in</a>
                </div>
            <?= $this->form ()->closeTag ();?><!-- form -->
        </section><!-- content -->
    </div>
</div>
