<nav class="navbar navbar-inverse footer-copyright" role="navigation">
    <footer>
        <ul class="list-inline text-center">
            <li>
                <a target="_blank" href="#">
                    <span class="fa-stack fa-lg">
                        <i class="fa fa-circle fa-stack-2x"></i>
                        <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                    </span>
                </a>
            </li>
        </ul> 
        <?php echo $this->Variable;?>
        <p class="copyright text-muted" dir="ltr">&copy; 2017 - <?= date('Y');?> by <a href="http://www.exchange.nijaz.info" >exchange</a></p>
        <p class="copyright text-muted" dir="ltr">Version: <?= $this->version;?></p>				 
    </footer>
</nav>